### PR TITLE
Document the async workflow

### PR DESCRIPTION
**Pull request by freeall**
Depends on https://github.com/FoundersAS/express-slack-events-listener/compare/master...freeall:patch-1

### CODE REVIEW

**Comment by joshuakarjala** [comment]
@freeall you get warning if you don't set 

`bodyParser.urlencoded({extended: false})`

**Comment by freeall** [comment]
Then they should do that :)

**Comment by joshuakarjala** [comment]
@freeall but then docs should say

```javascript
app.use('/slack_events', bodyParser.json(), bodyParser.urlencoded({extended: false}), slackEvents);
```

to not be misleading

**Comment by joshuakarjala** [comment]
hmm not complaining now - weird

**Pull request merged**
