### PR TITLE
Async flow for `onSlackEvent`

### PR DESCRIPTION
**Pull request by freeall**

### CODE REVIEW

**Comment by joshuakarjala** [comment]
hmm I guess then `onSlackEvent` can just do

```javascript
function (event, cb) {
    cb();
    // do stuff
}

for quick response times

**Comment by freeall** [comment]
If you want to store something in a db, and the db is down, then you want Slack to retry the event.
That's what this PR fixes

**Comment by joshuakarjala** [comment]
@freeall yes I get that. But in some use cases you might want to just reply to slack ASAP before doing in any IO on the server. My example was just verifying that this is still possible using this pattern :)

**Comment by freeall** [comment]
Ahh, yeah, sure :D You is correcto

**Pull request merged**
